In [1]:
import numpy as np
list = [10,44,34,0]
p = np.array(list)
print(p)

[10 44 34  0]


In [2]:
p.sum()

np.int64(88)

In [3]:
p.all()

np.False_

In [4]:
p.copy()

array([10, 44, 34,  0])

In [5]:
p.mean()

np.float64(22.0)

In [6]:
p.dtype

dtype('int64')

In [7]:
p.ndim

1

In [8]:
p.cumsum()

array([10, 54, 88, 88])

In [9]:
p.nonzero()

(array([0, 1, 2]),)

In [10]:
p.size

4

In [11]:
p.data

In [12]:
p.itemsize

8

In [13]:
list =np.array([[[2,3,5],[4,6,7],[3,8,9]],[[4,8,9],[8,4,6],[5,1,9]]])
list
#list.ndim

array([[[2, 3, 5],
        [4, 6, 7],
        [3, 8, 9]],

       [[4, 8, 9],
        [8, 4, 6],
        [5, 1, 9]]])

In [14]:
list.shape

(2, 3, 3)

In [15]:
list[0][1][1]

np.int64(6)

In [16]:
list[1][1][2]

np.int64(6)

In [17]:
list[0,1:,:-1]

array([[4, 6],
       [3, 8]])

In [18]:
list[:,1]

array([[4, 6, 7],
       [8, 4, 6]])

In [19]:
list1 = np.array([[[4,5,6,2],[8,6,9,0],[1,2,3,6]],[[2,3,5,6],[5,6,8,9],[1,6,0,9]]])
list1

array([[[4, 5, 6, 2],
        [8, 6, 9, 0],
        [1, 2, 3, 6]],

       [[2, 3, 5, 6],
        [5, 6, 8, 9],
        [1, 6, 0, 9]]])

In [20]:
list1[1,:,2]

array([5, 8, 0])

In [63]:
p = np.zeros((5,5),dtype=int)
p
p[0,0:] = 1
#p[0,4:] = 1
p
p[4,0:]=1
p
p[0:,-1]=1
p
p[0,0] = 1
p
p[1:,0] = 1
p




array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [103]:
t = np.zeros((8,8),dtype=int) 
t
t[0,::2] = 1
t[1,::-2] = 1
t[2,::2] = 1
t[3,::-2] =1
t[4,::2]= 1
t[5,::-2] = 1
t[6,::2] = 1
t[7,::-2] =1
t

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [104]:
k= np.tile(((0,1),(1,0)),(4,4))
k

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])