In [34]:
import numpy as np
list = [10,44,34,0]
p = np.array(list)
print(p)

[10 44 34  0]


In [13]:
p.sum()

np.int64(88)

In [35]:
p.all()

np.False_

In [17]:
p.copy()

array([10, 44, 34])

In [19]:
p.mean()

np.float64(29.333333333333332)

In [22]:
p.dtype

dtype('int64')

In [24]:
p.ndim

1

In [26]:
p.cumsum()

array([10, 54, 88])

In [28]:
p.nonzero()

(array([0, 1, 2]),)

In [30]:
p.size

3

In [32]:
p.data

In [33]:
p.itemsize

8