In [2]:
import numpy as np
list = [10,44,34,0]
p = np.array(list)
print(p)

[10 44 34  0]


In [3]:
p.sum()

np.int64(88)

In [4]:
p.all()

np.False_

In [5]:
p.copy()

array([10, 44, 34,  0])

In [6]:
p.mean()

np.float64(22.0)

In [7]:
p.dtype

dtype('int64')

In [8]:
p.ndim

1

In [9]:
p.cumsum()

array([10, 54, 88, 88])

In [10]:
p.nonzero()

(array([0, 1, 2]),)

In [11]:
p.size

4

In [12]:
p.data

In [13]:
p.itemsize

8

In [28]:
list =np.array([[[2,3,5],[4,6,7],[3,8,9]],[[4,8,9],[8,4,6],[5,1,9]]])
list
#list.ndim

array([[[2, 3, 5],
        [4, 6, 7],
        [3, 8, 9]],

       [[4, 8, 9],
        [8, 4, 6],
        [5, 1, 9]]])

In [29]:
list.shape

(2, 3, 3)

In [27]:
list[0][1][1]

np.int64(6)

In [32]:
list[1][1][2]

np.int64(6)

In [89]:
list[0,1:,:-1]

array([[4, 6],
       [3, 8]])

In [ ]:
list[:,1]

array([[[2, 3, 5],
        [4, 6, 7],
        [3, 8, 9]]])