In [1]:
#1 Q1. Create a 1■D NumPy array containing numbers from 1 to 20. After creating the
#array, print the array, its datatype, total number of elements and shape.
import numpy as np
k = [2,5,7,1,3,4,5,6]
t  = np.array(k)
t

array([2, 5, 7, 1, 3, 4, 5, 6])

In [2]:
t.shape

(8,)

In [3]:
t.dtype

dtype('int64')

In [4]:
#Q2. Create a 5×5 matrix filled entirely with zeros using NumPy. Display the matrix.
l= np.zeros((5,5),dtype=int)
l

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [5]:
#Q3. Create a 4×4 matrix filled with ones. Also print number of dimensions and size of
#the array.
k = np.zeros((4,4),dtype=int)
k[::-1] = 1
k.size

16

In [6]:
#Generate an identity matrix of size 6×6 and observe diagonal elements.
l = np.eye((6),dtype=int)
l

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [7]:
#Q5. Create an array using arange() function starting from 10 up to 50 with step size 5.
#Print the resulting array.
m = np.arange(10,50,5)
m

array([10, 15, 20, 25, 30, 35, 40, 45])

In [8]:
#Q6. Generate 10 evenly spaced values between 0 and 1 using linspace() and print them.
o = np.linspace(0,1,10)
o

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [9]:
#Q7. Create an array containing numbers from 1 to 10. Access and print first element,
#last element and elements from index position 2 to 6.
m = np.array([1,2,3,4,5,6,7,8,9,10])
m[0]#fisrt elememt
m[-1]#last element
m[1:6]


array([2, 3, 4, 5, 6])

In [10]:
#Q8. Create a 3×3 matrix with values of your choice. Extract and print the complete
#second row and third column.
y = np.array([[2,3,4],
                [4,5,6],
                [6,7,8]])
y
y.ndim

2

In [11]:
y[1]

array([4, 5, 6])

In [12]:
y[:,2]

array([4, 6, 8])

In [13]:
#Q9. Reverse a given NumPy array using slicing technique and print original and
#reversed array
p  = np.array([1,2,3,4,5,6,7,8,9,10])
p
p[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [14]:
#Create two arrays a=[10,20,30,40] and b=[1,2,3,4]. Perform element■wise
#addition, subtraction, multiplication and division.
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
c = a+b
c
c = a*b
c
c = a-b
c

array([ 9, 18, 27, 36])

In [15]:
#For array [4,9,16,25], compute square, cube and square root of each element.
l= np.array([4,9,16,25])
m = l*l
m
p = l*l*l
p

array([   64,   729,  4096, 15625])

In [16]:
#Create any 2■D array and calculate sum of all elements as well as column■wise sum.
m = np.array([[3,4,6],
              [8,2,1]])
n = np.array([[3,4,5],
              [9,8,7]])
l = m+n
l

array([[ 6,  8, 11],
       [17, 10,  8]])